config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Devise engine routes
  devise_for :users

  # Swagger routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Defines the root path route ("/")
  root "home#show"

  # ---------- Namespace: Administration
  namespace :administration do
    get 'users',           to: "/administration/users#index"
    get 'data_imports',    to: "/administration/data_imports#new"

    resources :users do
      member do
        patch :set_playground
        post :activate
      end
    end

    resources :groups do
      member do
        post :activate
      end
    end

    resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
        member do
          post :activate
        end
    end

    resources :parameters

    resources :data_imports
  end  
end

app/controllers/administration/groups_controller.rb
class Administration::GroupsController < AdministrationController
  include TerritoriesHelper, OrganisationsHelper
# Check for active session
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_group, only: [:show, :edit, :update, :destroy, :activate]

    # Initialise breadcrumbs for the resulting view
    #before_action :set_breadcrumbs, only: [:show, :edit, :update]

    # GET /groups
    # GET /groups.json
    def index
      @groups = Group.joins(translated_groups).
                      where("groups.owner_id = ? or ? is null", params[:owner], params[:owner]).
                      visible.
                      select(index_fields).
                      order(order_by)

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @groups }
      end
    end

  # GET /groups/1
  # GET /groups/1.json
  def show
    ### Retrieved by Callback function
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    ### Retrieved by Callback function
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.metadata_setup(current_user)

    respond_to do |format|
      if @group.save
        format.html { redirect_to [:administration, @group], notice: t('GroupCreated') } #'Group was successfully created.'
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @group.updated_by = current_login

    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to [:administration, @group], notice: t('GroupUpdated') } #'Group was successfully updated.'
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /groups/1
  # POST /groups/1.json
  def activate
    ### Retrieved by Callback function
    @group.set_as_active(current_login)

    respond_to do |format|
      if @group.save
          format.html { redirect_to [:administration, @group], notice: t('GroupRecalled') } #'Business landsacpe was successfully recalled.'
          format.json { render json: @group, status: :created, location: @group }
        else
          format.html { redirect_to [:administration, @group], notice: t('GroupRecalledKO') } #'Business landsacpe  cannot be recalled.'
          format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.set_as_inactive(current_login)

    respond_to do |format|
      format.html { redirect_to administration_groups_url, notice: t('GroupDeleted') } #'Group was successfully destroyed.'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # breadcrumbs calculation from controllers helpers
    def set_breadcrumbs
      @breadcrumbs = @group.name[current_language.to_s]
    end

    ### queries tayloring
    def owners
      User.arel_table.alias('owners')
    end

    def groups
      Group.arel_table
    end

    def organisations
      Organisation.arel_table
    end

    def territories
      Territory.arel_table
    end


    def translated_groups
      groups.
      join(owners).on(groups[:owner_id].eq(owners[:id])).
      join(organisations).on(groups[:organisation_id].eq(organisations[:id])).
      join(territories).on(groups[:territory_id].eq(territories[:id])).
      join_sources
    end

    def index_fields
      [ groups[:id], 
        groups[:code], 
        groups[:name], 
        groups[:description], 
        groups[:territory_id], 
        groups[:organisation_id], 
        organisations[:name].as("organisation_name"),
        territories[:name].as("territory_name"),
        groups[:status_id], 
        groups[:updated_by], 
        groups[:updated_at], 
        groups[:is_active],
        owners[:name].as("owner_name"),
        Arel::Nodes::SqlLiteral.new("case
          when not groups.is_active then '0'
          else '1'
          end").as("calculated_status")
      ]
    end

    def order_by
      [groups[:code].asc]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:role, 
                                    :territory_id, 
                                    :organisation_id, 
                                    :created_by, 
                                    :updated_by, 
                                    :code,
                                    name: {}, 
                                    description: {}, 
                                    role_ids: [])
    end
end

app/controllers/administration/parameters_controller.rb
class Administration::ParametersController < AdministrationController
  # Check for active session
    before_action :authenticate_user!
    load_and_authorize_resource

  # Retrieve current parameter
    before_action :set_parameter, only: [:show, :edit, :update, :destroy]

  def new
    # If the parameteris created as the child of another parameter, then the parent parameteris assigned as superior
    @parameters_list = ParametersList.find(params[:parameters_list_id])
    @parameter= @parameters_list.parameters.build()
    render layout: false
  end

  def edit
    # parameter retrieved by callback
    render layout: false
  end

  def create
    @parameters_list = ParametersList.find(params[:parameters_list_id])
    @parameter= @parameters_list.parameters.build(parameter_params)

    respond_to do |format|
      if @parameter.save
        format.html { redirect_back fallback_location: root_path, notice: t('.Success') } #'Variable was successfully updated.'
        format.json { head :no_content }
      else
        format.html { redirect_back fallback_location: root_path, notice: "#{t('.Failure')}: #{@parameter.errors.full_messages.join(',')}" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # parameter retrieved by callback
    @parameters_list = ParametersList.find(@parameter.parameters_list_id)

    respond_to do |format|
      if @parameter.update_attributes(parameter_params)
        format.html { redirect_back fallback_location: root_path, notice: t('.Success') } #'Variable was successfully updated.'
        format.json { head :no_content }
      else
        format.html { redirect_back fallback_location: root_path, notice: "#{t('.Failure')}: #{@parameter.errors.full_messages.join(',')}" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    # parameterretrieved by callback
    render layout: false

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parameter}
      format.csv { send_data @parameter.to_csv }
      format.xlsx # uses specific template to render xml
    end
  end

  def destroy
    # parameterretrieved by callback
    @parameter.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: t('.Success') } # 'Parameter was successfully deleted.'
      format.json { head :no_content }
    end
  end

  ### private functions
  private

  ### Use callbacks to share common setup or constraints between actions.
    # Retrieve current parameter
    def set_parameter
      @parameter= Parameter.find(params[:id])
      @parameters_list = ParametersList.find(@parameter.parameters_list_id)
    end

    # breadcrumbs calculation from controllers helpers
    def set_breadcrumbs
      @breadcrumbs = breadcrumbs(@parameter)
    end

    ### queries tayloring

    def parameters
      Parameter.arel_table
    end

    def index_fields
      [ parameters[:id], 
        parameters[:code], 
        parameters[:sort_code], 
        # Arel::Nodes::SqlLiteral.new("(name -> '#{current_language.to_s}') as name"), 
        # Arel::Nodes::SqlLiteral.new("(description -> '#{current_language.to_s}') as description"), 
        parameters[:name],
        parameters[:description],
        parameters[:property], 
        parameters[:scope], 
        parameters[:active_to], 
        parameters[:active_from]
      ]
    end

    def order_by
      [parameters[:sort_code].asc]
    end

  ### strong parameters
  def parameter_params
    params.require(:parameter).permit(:playground_id, :parameters_list_id, :code, :property, :scope, :active_from, :active_to, name: {}, description: {})
  end

end

app/controllers/administration/parameters_lists_controller.rb
class Administration::ParametersListsController < AdministrationController
# Check for active session
  before_action :authenticate_user!
  load_and_authorize_resource

# Retrieve current list
  before_action :set_parameters_list, only: [:show, :edit, :update, :export, :destroy]


  before_action :set_statuses_list, only: [:new, :edit, :update, :create]

  # Initialise breadcrumbs for the resulting view
  #before_action :set_breadcrumbs, only: [:show, :edit, :update]

  # GET /parameters_list
  # GET /parameters_list.json
  def index
    @parameters_lists = ParametersList.joins(translated_parameters_lists).
                                        where("parameters_lists.owner_id = ? or ? is null", params[:owner], params[:owner]).
                                        visible.
                                        select(index_fields).
                                        order(order_by)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parameters_lists }
      format.csv { send_data @parameters_lists.to_csv }
      format.xlsx # uses specific template to render xml
    end
  end

  # GET /parameters_list/1
  # GET /parameters_list/1.json
  # GET /parameters_list/1.csv
  # GET /parameters_list/1.xlsx
  def show
    ### Retrieved by Callback function

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parameters_list.parameters }
      format.csv { send_data @parameters_list.parameters.to_csv }
      format.xlsx {render xlsx: "show", filename: "#{@parameters_list.code}_parameters.xlsx", disposition: 'inline'} # uses specific template to generate the a file
    end
  end

  # GET /parameters_list/new
  def new
    @parameters_list = ParametersList.new
    @parameters = @parameters_list.parameters.order(:sort_code).paginate(page: params[:page], :per_page => paginate_lines)
  end

  # GET /parameters_list/1/edit
  def edit
    ### Retrieved by Callback function
    #check_translations(@parameters_list)
  end

  # POST /parameters_list
  # POST /parameters_list.json
  def create
    @parameters_list = ParametersList.new(parameters_list_params)
    @parameters_list.metadata_setup(current_user)
    # Build translated json fields
    all_translations(@parameters_list)

    respond_to do |format|
      if @parameters_list.save
        format.html { redirect_to [:administration, @parameters_list], notice: t('PLCreated') } #'List of parameters was successfully created.'
        format.json { render action: 'show', status: :created, location: @parameters_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @parameters_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parameters_list/1
  # PATCH/PUT /parameters_list/1.json
  def update
    ### Retrieved by Callback function
    @parameters_list.updated_by = current_login
    # Build translated json fields
    all_translations(@parameters_list)

    respond_to do |format|
      if @parameters_list.update(parameters_list_params)
        format.html { redirect_to [:administration, @parameters_list], notice: t('PLUpdated') } #'List of parameters was successfully updated.'
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parameters_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # Reactivate deleted parameters_list
  def activate
    ### Retrieved by Callback function
    @parameters_list.set_as_active(current_login)
    respond_to do |format|
      format.html { redirect_to [:administration, @parameters_list], notice: t('PLRecalled')  }
      format.json { head :no_content }
    end
  end

  # DELETE /parameters_list/1
  # DELETE /parameters_list/1.json
  def destroy
    ### Retrieved by Callback function
    @parameters_list.set_as_inactive(current_login)
    respond_to do |format|
      format.html { redirect_to administration_parameters_lists_url, notice: t('PLDeleted') } #'Parameters List was successfully deleted.'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_parameters_list
      @parameters_list = ParametersList.includes(:owner, :status).find(params[:id])
      @parameters_export = Parameter.visible.where("parameters_lists.id = ?", @parameters_list.id)
      @parameters = @parameters_list.parameters.order(:sort_code).paginate(page: params[:page], :per_page => paginate_lines)
    end

    # breadcrumbs calculation from controllers helpers
    def set_breadcrumbs
      @breadcrumbs = breadcrumbs(@parameters_list)
    end

    ### queries tayloring
    def owners
      User.arel_table.alias('owners')
    end

   def parameters_lists
      ParametersList.arel_table
    end

    def parameters
      Parameter.arel_table
    end

    def translated_parameters_lists
      parameters_lists.
      join(owners).on(parameters_lists[:owner_id].eq(owners[:id])).
      join_sources
    end

    def translated_parameters
      parameters.
      join(parameters_lists).on(parameters[:parameters_list_id].eq(parameters_lists[:id])).
      join_sources
    end

    def index_fields
      [ parameters_lists[:id], 
        parameters_lists[:owner_id], 
        parameters_lists[:code], 
        parameters_lists[:name], 
        parameters_lists[:description], 
        parameters_lists[:status_id], 
        parameters_lists[:updated_by], 
        parameters_lists[:updated_at], 
        parameters_lists[:is_active],
        owners[:name].as("owner_name"),
        Arel::Nodes::SqlLiteral.new("case
          when not parameters_lists.is_active then '0'
          else '1'
          end").as("calculated_status")
      ]
    end

    def order_by
      [parameters_lists[:code].asc]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameters_list_params
      params.require(:parameters_list).permit(:code, :status_id, :sort_code, name: {}, description: {}, 
      parameters_attributes: [:code, :property, :scope, :active_from, :active_to, :_destroy, :id, name: {}, description: {}])
    end
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  #layout 'administration'
end

app/views/administration/parameters_lists/_form.html.erb
<%= form_with model: [:administration, @parameters_list], local: true, html: {id: "edit_form"} do |f| %>

  <%= render partial: "shared/error_list", locals: { errors: @parameters_list.errors } %>

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#definition" data-toggle="tab"> <%= t('Definition') %></a></li>
    </ul>
    <div class="tab-content">

      <div class="tab-pane active" id="definition">
        <!-- Tab content for Definition -->

        <%= render partial: "shared/object_definition_form", locals: {this_object: @parameters_list, f: f} %>



      </div>
    </div>
  </div>
<% end %>

app/views/administration/parameters_lists/edit.html.erb
<% provide(:title, (t('ManagingPms'))) %>

<% provide :page_heading do %>
  <%= render partial: "shared/heading", locals: {this_object: @parameters_list} %>
<% end %>

<% provide :breadcrumbs do %>
  <ol id="breadcrumbs" class="breadcrumbs">
    <li>
      <a href="/" title="<%= t("Display") %>" class="fa fa-home"></a>
    </li>
    <li>
      <%= link_to @parameters_list.name[current_language.to_s] %>
    </li>
  </ol>
<% end %>

<% provide :navigation do %>
  <%= render partial: "shared/edit_view_navigation" %>
<% end %>

<% provide :actions do %>
  <%= render partial: "shared/object_edit_actions", locals: {this_object: @parameters_list } %>
<% end %>

<%= render 'form' %>

app/views/administration/parameters_lists/index.html.erb
<% provide(:title, t('ManagingParametersLists')) %>

<% provide(:page_heading, t('ParametersLists')) %>


<% provide :navigation do %>
  <%= render partial: "shared/index_view_navigation", locals: {this_object: ParametersList} %>
<% end %>

<% provide :actions do %>
  <%= render partial: "shared/object_index_actions", locals: {this_object: ParametersList } %>
<% end %>

<%= render partial: "shared/object_index", locals: {this_index: @parameters_lists} %>

app/views/administration/parameters_lists/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% ParametersList.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @parameters_lists.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/administration/parameters_lists/new.html.erb
<% provide(:title, (t('ManagingPms'))) %>

<% provide :page_heading do %>
    <%= t('NewPm') %>
<% end %>

<% provide :navigation do %>
  <%= render partial: "shared/edit_view_navigation" %>
<% end %>

<% provide :actions do %>
  <%= render partial: "shared/object_edit_actions", locals: {this_object: @parameters_list } %>
<% end %>

<%= render 'form' %>

app/views/administration/parameters_lists/show.html.erb
<% provide(:title, (t('ManagingParametersLists'))) %>
<% provide(:page_class, 'page-view-details') %>

<% provide :page_heading do %>
  <%= render partial: "shared/heading", locals: {this_object: @parameters_list} %>
<% end %>

<% provide :breadcrumbs do %>
  <ol id="breadcrumbs" class="breadcrumbs">
    <li>
      <a href="/" title="<%= t("Display") %>" class="fa fa-home"></a>
    </li>
    <li>
      <%= link_to @parameters_list.name[current_language.to_s] %>
    </li>
  </ol>
<% end %>

<% provide :navigation do %>
  <%# render partial: "shared/show_view_navigation", locals: {this_object_parent: @parameters_list.parent, this_object_index: administration_parameters_lists_path} %>
<% end %>

<% provide :actions do %>
  <%= render partial: "shared/object_actions", locals: {this_object: @parameters_list } %>
<% end %>

<% provide :technical_details do %>
  <%= render partial: "shared/object_ownership",
      locals: {this_object: @parameters_list} %>
<% end %>

<% provide :information do %>
  <div class="row">
    <div class="col-md-6">
      <%= render partial: "shared/object_definition", locals: {
          this_object: @parameters_list,
          smallTextarea: true,
          isTechnical: true} %>
    </div>
  </div>
<% end %>

<%= render layout: "layouts/collapsible_details",
    locals: {tabs_content: [ :information ],
    title: t('Parameters')}  do %>

<% end %>

<hr />

<section class="tabbable">

  <div class="tabbable">

    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#parameters" data-toggle="tab"><%= t('.Parameters') %></a></li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="parameters">

        <div class="mat-button-group">
          <%= link_to administration_parameters_list_path(@parameters_list, format: "xlsx"), class: "mat-flat-button mat-button-base mat-primary" do %>
            <span class="fa fa-file-excel"></span>
            Export to Excel
          <% end %>
          <%= link_to new_administration_parameters_list_parameters_import_path(@parameters_list), class: "mat-flat-button mat-button-base mat-primary" do %>
            <span class="fa fa-file-alt" %></span>
            <%= t('.ImportParameters') %>
          <% end %>
        </div>

        <%= will_paginate @parameters %>

        <table class="table table-align-top table-hover">
          <tr>
            <th> <%= t('.Code') %> </th>
            <th> <%= t('.Property') %> </th>
            <th> <%= t('.Name') %> </th>
            <th> <%= t('.Description') %> </th>
            <th> <%= t('.TaskScope') %> </th>
            <th> <%= t('.ValidFrom') %> </th>
            <th> <%= t('.ValidTo') %> </th>
            <th class="col-min-nw">
              <%= link_to new_administration_parameters_list_parameter_path(@parameters_list), title: t('.New'), data: { toggle: "modal", target: "#childModal" }, class: "mat-flat-button mat-button-base mat-primary" do%>
                <span class="fa fa-plus-square" %></span>
                <%= t("New") %>
            <% end %>
            </th>
          </tr>

          <tbody>
            <% if @parameters.count > 0 %>
              <% @parameters.each do |parameter| %>
                <tr>
                  <td class="no-wrap"> <%= parameter.code %> </td>
                  <td class="no-wrap"> <%= parameter.property %> </td>
                  <td class="no-wrap"> <%= parameter.name[current_language.to_s] %> </td>
                  <td class="no-wrap"> <%= parameter.description[current_language.to_s] %> </td>
                  <td> <%= parameter.scope %> </td>
                  <td> <%= format_date(parameter.active_from) %></td>
                  <td> <%= format_date(parameter.active_to) %></td>
                  <td class="cell-with-button cell-nw">
                    <%= link_to administration_parameters_list_parameter_path(@parameters_list, parameter), title: t('.Show'), data: { toggle: "modal", target: "#childModal" }, class: "mat-icon-button mat-button-base mat-secondary" do%>
                      <span class="fa fa-eye"></span>
                    <% end %>
                    <%= link_to edit_administration_parameters_list_parameter_path(@parameters_list, parameter), title: t('.Edit'), data: { toggle: "modal", target: "#childModal" }, class: "mat-icon-button mat-button-base mat-secondary" do%>
                      <span class="fa fa-edit"></span>
                    <% end %>
                    <%= link_to administration_parameter_path(parameter), title: t('Delete'), data: { confirm: t("SureDelete")  }, method: :delete, class: "mat-icon-button mat-button-base mat-warn" do%>
                      <span class="fa fa-trash"></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td class="cell-empty" colspan=8">
                  <p class="alert alert-info">
                    <%= t('.NoChildren') %>
                  </p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= will_paginate @parameters %>

      </div> <!-- closes parameters pane -->

    </div>

</section>