config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Devise engine routes
  devise_for :users

  # Swagger routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Defines the root path route ("/")
  root "home#show"

  # ---------- Namespace: Administration
  namespace :administration do
    get 'users',           to: "/administration/users#index"
    get 'data_imports',    to: "/administration/data_imports#new"

    resources :users do
      member do
        patch :set_playground
        post :activate
      end
    end

    resources :groups do
      member do
        post :activate
      end
    end

    resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
        member do
          post :activate
        end
    end

    resources :parameters

    resources :data_imports
  end  
end

app/views/layouts/_footer.html.erb
<footer class="application-footer offcanvas-main application-footer-sm">

  <div class="footer-item footer-item-info">
    <small orfooterinfo="">© <%= Time.current.year %> Open Data Quality - <%= $VERSION %></small>
  </div>

  <ul class="footer-item footer-item-list">
    <li><%= link_to $Organisation, $Organisation_URL %></li>
    <li><%= link_to t('Help'), help_path('help-index') %></li>
    <li><%= link_to t('License'), help_path('License') %></li>
  </ul>

  <%= debug(params) if Rails.env.development? %>
</footer>

app/views/layouts/_header.html.erb

<header class="application-header <%= content_for?(:large_header) ? '' : 'application-header-md' %> offcanvas-main application-header-animate application-header-sticky">
  <div class="header <%= Rails.env %>">
    <div class="application-header-title">
      <div class="application-brand">
        <a tabindex="-1" href="/">
          <img alt="Back to home" src="/assets/<%= $Logo %>">
        </a>
        <h1 class="application-brand-app-title">
          <b><%= Rails.env.production? ? "" : "#{Rails.env.capitalize} - " %> </b><%= yield(:page_heading || :title) %>
        </h1>
      </div>
    </div>

    <div class="application-header-controls">
      <h2 class="sr-only">Contrôles</h2>
      <ul class="header-controls" role="menu">
        <% if user_signed_in? %>
          <li id="language-picker-ct" class="control-item" role="menuitem">
            <nav id="language-picker">
              <% parameters_for('languages').each do |language| %>
                <%= render partial: "shared/language_picker_link", locals: {label: language.code, locale: language.property} %>
              <% end %>
            </nav>
          </li>
          <li class="control-item" role="menuitem">
            <%= link_to administration_user_path(current_user), title: t("User") + ": " + current_login, class: "nav-link control-link" do %>
              <span class="control-icon fa fa-user"></span>
            <% end %>
          </li>
          <li class="control-item" role="menuitem">
            <%= link_to destroy_user_session_path, method: "delete", title: t("Sign_out"), class: "nav-link control-link" do %>
              <span class="control-icon fa fa-sign-out-alt"></span>
            <% end %>
          </li>
        <% else %>
          <li class="control-item" role="menuitem">
            <%= link_to new_user_session_path, title: t("Sign_in"), class: "nav-link control-link" do %>
              <span class="control-icon fa fa-sign-in-alt"></span>
            <% end %>
          </li>
        <% end %>

        <li class="control-item" role="menuitem">
          <%= link_to help_path([namespace, controller_name], action_name), title: t("Help"), class: "nav-link control-link" do %>
            <span class="control-icon fa fa-info-circle"></span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rails_poc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="<%= yield(:page_class) %>">

    <div class="application material application-fixed offcanvas footer-sm has-overlay">

      <%= render "layouts/header" %>

      <div class="application-content offcanvas-main" id="content" role="main" tabindex="-1">

        <div class="alert-compatibility default-layout">
          <div class="alert alert-error">
            <span class="sr-only">Error</span>
            <h4>Unsupported browser!</h4>
            <p class="lead">Please note that your browser, Internet Explorer 9 or earlier, is deprecated.</p>
            <p>We recommend upgrading to the
              <a href="https://www.microsoft.com/en-us/windows/microsoft-edge" rel="noopener" target="_blank">latest version</a>.</p>
            <p>If you are using IE 10 or above, make sure you
              <a href="https://support.microsoft.com/en-us/help/17471" rel="noopener" target="_blank">turn off "Compatibility View".</a>
            </p>
          </div>
        </div>

        <div class="application-content-viewport">
          <main class="empty-layout">
            <div class="column-layout">

              <div class="column-main">
                <div class="sticky">
                  <section class="ui-component sticky">
                    <div class="sticky-main default-layout">
                      <%= yield %>
                    </div>
                  </section>
                </div>
              </div>

              <% if content_for?(:error_list) %>
                <div id="column-right" class="column-right column-narrow d-print-none" role="complementary">
                  <button class="column-toggle-right" type="button">
                    <span class="sr-only">i18n.oblique.column.right.toggle</span>
                  </button>
                  <div class="column-content default-layout">
                    <%= yield(:error_list) %>
                  </div>
                </div>
              <% end %>
            </div>
          </main>
        </div><!-- end: div.application-content-viewport -->
      </div><!-- end: div#content -->

      <!-- Child Modal window for generic use -->
      <aside class="modal fade modal-remote" id="childModal" tabindex="-1" role="dialog" aria-labelledby="childModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
          <div class="modal-content"></div>
        </div>
      </aside>

      <%= render "layouts/footer" %>

    </div><!-- end: div.application-->

    <%= render "shared/inline_scripts" %>

  </body>
</html>